### PR TITLE
removed unreachable code (duplicated return), fixed parsing of disconnect response

### PR DESCRIPTION
**Pull request by daniel-faber**

### CODE REVIEW

**Comment by LinusU** [comment]
(I have only looked at and approved the first commit)

**Comment by daniel-faber** [comment]
Hmm, I didn't know that pushing to the same branch again extends the existing pull request. Now we have two completely unrelated commits here. I'm Sorry, this is my first pull request at all.

**Comment by LinusU** [comment]
No problem, there is first for everything! It would be nice to have this as separate PRs though. I would recommend to never open a pull request from your "master" branch, but instead creating one branch per "feature", and then open a pull request from that branch :)

**Comment by daniel-faber** [comment]
Okay, I will close this one and create two seperate PRs...

**Pull request closed without merging**
